# Site settings
title: Ziwei Zhao
description: 'A third year Computer Science student at Uwaterloo'
url: 'http://ziweizhao.com'
baseurl: '/ziweizhao.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ziwei Zhao'
  email: ziweizhao1122@gmail.com
  facebook_username: ziweizhao1122
  github_username:  ziweizhao
  linkedin_username:  ziweizhao1122

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
